replicaCount: 1

image:
  repository: mcr.microsoft.com/azure-storage/azurite
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    blob: 10000
    queue: 10001
    table: 10002
  nodePorts:
    blob: 30000
    queue: 30001
    table: 30002


persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""

resources: 
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
